routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return redirect('login');

});

Auth::routes();
Route::group(['middleware' => ['auth']], function() {

    Route::resource('roles','RoleController');    
    Route::get('/home', 'HomeController@index');
    Route::get('/change-password','UsersController@changePassword');
    Route::post('/change-password','UsersController@postChangePassword');
    Route::resource('/users','UsersController');
    Route::resource('/company','CompanyController');
    Route::get('/branchList/{companyId}','BranchController@branchList');
    Route::resource('/branch','BranchController');
    Route::resource('/tag-user','TagUserController');
    Route::resource('/zone','ZoneController');
    Route::get('/zoneList/{branchId}','ZoneController@zoneList');
    Route::get('/current-occupancy','CameraTransactionController@currentOccupancy');
    Route::get('/foot-fall','CameraTransactionController@footFall');
    Route::get('/violation','CameraTransactionController@violation');
    Route::post('/postzonesanitisation','HomeController@postZoneSanitisation');
    Route::get('/zone-notification','ZoneController@zoneNotification');

    #Route::get('/current-occupany','ZoneController@currentOccupany');
//currentOccupany
    Route::get('/device','CameraController@device');
    Route::get('/foot-fall-device/{id}','CameraTransactionController@footFallDevice')->name('foot_by_device');
    Route::resource('/camera','CameraController');
    Route::get('getZoneOccupancy','CameraTransactionController@getZoneOccupancy');
    Route::get('home-page','HomeController@homePage')->name('home');
    Route::get('chart_file_content','CameraTransactionController@chartFileContent')->name('chart_content');


});

app/TagUser.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class TagUser extends Model
{
    use SoftDeletes;
    protected $fillable=['company_id','branch_id','username','password','status'];
}

app/Http/Controllers/Api/TagUserController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\ApiController;
use Validator;
use App\TagUser;
use App\Camera;
use Illuminate\Support\Facades\DB;
class TagUserController extends ApiController
{
    function login(Request $request){
        $validator = Validator::make($request->all(), [
            'username' => 'required',
            'password' => 'required',
        ]);
        if ($validator->fails()) {
            $response['status']  =false;
            $response['message'] = trans('message.validation');;
            $response['data']    = $validator->errors();
            return $this->sendResponse($response);
        }

        $username = $request->username;
        $password = $request->password;
        $tagUser = TagUser::select('company_name','branch_name','tag_users.id','tag_users.company_id','tag_users.branch_id')
                            ->join('companies','company_id','=','companies.id')
                            ->join('branches','branch_id','=','branches.id')
                            ->where(['username'=>$username,'password'=>$password])
                            ->first();
        $status=false; 
        $message="Please try again.";
        $data=[];
        if($tagUser){
            $status=true;
            $message="Tag user found.";
            $data['tag_user_id'] = $tagUser->id;
            $data['company_id'] = $tagUser->company_id;
            $data['branch_id']  = $tagUser->branch_id;
            $data['company_name'] = $tagUser->company_name;
            $data['branch_name']  = $tagUser->branch_name;
            $branch_id=$tagUser->branch_id;
        }
        $response = array();
        $response['status']     = $status;
        $response['message']    = $message;
        $response['data']       = $data;
        
        return $this->sendResponse($response);
}

function camera(Request $request){
    $validator = Validator::make($request->all(), [
        'branch_id' => 'required',
    ]);
    if ($validator->fails()) {
        $response['status']  =false;
        $response['message'] = trans('message.validation');;
        $response['data']    = $validator->errors();
        return $this->sendResponse($response);
    }

    $branch_id = $request->branch_id;
    $cameras = Camera::where(['branch_id'=>$branch_id,'status'=>1])
                        ->get();
    $status=false; 
    $message="Please try again.";
    $data=[];
    if($cameras){
        $status=true;
        $message="Camera found.";
        $data['cameras']  = $cameras;
       
    }
    $response = array();
    $response['status']     = $status;
    $response['message']    = $message;
    $response['data']       = $data;
    
    return $this->sendResponse($response);
}

}

app/Http/Controllers/TagUserController.php
<?php

namespace App\Http\Controllers;

use App\TagUser;
use Illuminate\Http\Request;
use App\User;
use App\Company;
use App\Branch;
class TagUserController extends Controller
{
    private $companyList;
    public function __construct()
    {
        $this->companyList=Company::companyList();
        $this->middleware('auth');
        $this->middleware('permission:tag-user-list',['only' => ['index']]);
        $this->middleware('permission:tag-user-create', ['only' => ['create','store']]);
        $this->middleware('permission:tag-user-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:tag-user-delete', ['only' => ['destroy']]);
        
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $userInfo= User::getUserInfo();
        $tag_users = TagUser::select('tag_users.id','username','tag_users.created_at','company_name','branch_name')
        ->join('companies','company_id','=','companies.id')
        ->join('branches','branch_id','=','branches.id')
        ->where(function($query) use ($userInfo){
            $company_id=$userInfo['company_id'];
            $branch_id=$userInfo['branch_id'];
            if($company_id){
                $query->where('tag_users.company_id',$company_id);
            }
            if($branch_id){
                $query->where('tag_users.branch_id',$branch_id);
            }
        })
        ->orderBy('tag_users.id','desc')->get();
        $i=0;
        return view('tag_user.index',compact('tag_users','i'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $userInfo= User::getUserInfo();
        $branches = Branch::branchByCompanyId($userInfo['company_id']);
        return view('tag_user.create',compact('userInfo','branches'))->with(['companyList'=>$this->companyList]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'company_id' => 'required',
            'branch_id' => 'required',
            'username' => 'required',
            'password' => 'required|min:6',
        ]);

        $input = $request->all();
        
        $tagUser = TagUser::create($input);
        if($tagUser){
            return redirect()->route('tag-user.index')

            ->with('success','Tag User created successfully');
        }
        else{

        }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\TagUser  $tagUser
     * @return \Illuminate\Http\Response
     */
    public function show(TagUser $tagUser)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\TagUser  $tagUser
     * @return \Illuminate\Http\Response
     */
    public function edit(TagUser $tagUser)
    {
        $userInfo= User::getUserInfo();
        $branches = Branch::branchByCompanyId($tagUser->company_id);
        return view('tag_user.edit',compact('tagUser','userInfo','branches'))->with(['companyList'=>$this->companyList]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\TagUser  $tagUser
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, TagUser $tagUser)
    {
        $this->validate($request, [
            'company_id' => 'required',
            'branch_id' => 'required',
            'username' => 'required',
            'password' => 'required|min:6',
        ]);


        $tagUser->company_id     = $request->company_id;
        $tagUser->branch_id      = $request->branch_id;
        $tagUser->username      = $request->username;
        $tagUser->password         = $request->password;
        if($tagUser->save()){
            return redirect()->route('tag-user.index')

            ->with('success','Tag User updated successfully');
        }
        else{
            return redirect()->route('tag-user.index')

            ->with('warning','Please try again.');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\TagUser  $tagUser
     * @return \Illuminate\Http\Response
     */
    public function destroy(TagUser $tagUser)
    {
        $tagUser->delete();
        return redirect()->route('tag-user.index')
    
                            ->with('success','Tag user deleted successfully');
    }
}

resources/views/tag_user/changepassword.blade.php
@extends('layouts.admin')

@section('content')
 
<div class="row">
  <div class="col-12"> <div class="page-title padleft20">Change Password</div></div>
  <!-- <div class="col-6">
    <div class="btn">
          <a href="{{url('users')}}" class="back btn-primary btn no-radius ">Back </a> 
      </div>
  </div> -->

  <div class="col-12"><div class="bottom-border"></div></div>
    

@if (count($errors) > 0)
  <div class="col-md-12">
  <div class="alert-message alert alert-danger">
    <Label>Whoops!</Label> There were some problems with your input.<br><br>
    <ul>
       @foreach ($errors->all() as $error)
         <li>{{ $error }}</li>
       @endforeach
    </ul>
  </div>
  </div>
  
@endif

  
</div><!--/.row-->
<div class="card mt-3">
  <div class="card-body">


  {!! Form::open(array('url' => 'change-password','method'=>'POST','class'=>'form')) !!}

   <div class="row">    
    <div class="col-xs-12 col-sm-12 col-md-6">
        <div class="form-group @error('password') has-error @enderror ">
            <Label class="req">Password</Label>
            {!! Form::password('password', array('id'=>'password','placeholder' => 'Password','class' => 'form-control')) !!}
              @error('password')
    		<span class="help-block">{{ $message }}</span> 
			@enderror
            
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6">
        <div class="form-group @error('confirm-password') has-error @enderror ">
            <Label class="req">Confirm Password</Label>
            {!! Form::password('confirm-password', array('id'=>'confirm-password','placeholder' => 'Confirm Password','class' => 'form-control')) !!}
            @error('confirm-password')
    		<span class="help-block">{{ $message }}</span> 
			@enderror
            
        </div>
    </div>
</div>



<div class="row">
	<div class="col-md-2">
        <button type="submit" class="btn btn-primary btn-block">Change Password</button>
    
    </div>
</div>

<script>
    $(document).ready(function () {
    
      

	$('.form').validate({ 
        rules: {
			password: {
                required: true,
                minlength:6,
                maxlength:15
            },
			'confirm-password': {
                required: true,
                equalTo: "#password"
            }
	    }
    });
});
</script>


{!! Form::close() !!}
</div>
</div>

@endsection

resources/views/tag_user/create.blade.php
@extends('layouts.admin')

@section('content')

    <div class="row">
        <div class="col-12">
            <div class="page-title padleft20">Add New App User</div>
        </div>
        <div class="col-6">
            <div class="btn">
                <a href="{{ url('tag') }}" class="back btn-primary btn no-radius ">Back </a>
            </div>
        </div>

        <div class="col-12">
            <div class="bottom-border"></div>
        </div>


        @if (count($errors) > 0)
            <div class="col-md-12">
                <div class="alert-message alert alert-danger">
                    <Label>Whoops!</Label> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            </div>

        @endif


    </div>
    <!--/.row-->
    <div class="card">
        <div class="card-body">


            {!! Form::open(['route' => 'tag-user.store', 'method' => 'POST', 'class' => 'form']) !!}
            <div class="row">
                @if ($userInfo['companyListShow'])
                    <div class="col-xs-12 col-sm-12 col-md-6">
                        <div class="form-group">
                            <Label class="req">Company List</Label>

                            {!! Form::select('company_id', $companyList, null, ['placeholder' => 'Select Company', 'class'
                            => 'form-control']) !!}
                        </div>
                    </div>
                @else
                    {!! Form::hidden('company_id', $userInfo['company_id'], ['placeholder' => '', 'class' =>
                    'form-control']) !!}

                @endif
                @if (!$userInfo['branch_id'])
                    <div class="col-xs-12 col-sm-12 col-md-6">
                        <div class="form-group">
                            <Label class="req">Branch Name</Label>
                            {!! Form::select('branch_id',$branches, null, ['placeholder' => 'Select Branch', 'class' =>
                            'form-control']) !!}
                        </div>
                    </div>
                @else
                    {!! Form::hidden('branch_id', $userInfo['branch_id'], ['placeholder' => '', 'class' => 'form-control'])
                    !!}
                @endif



                <div class="col-xs-12 col-sm-12 col-md-6">
                    <div class="form-group">
                        <Label class="req">Login ID</Label>
                        {!! Form::text('username', null, ['placeholder' => '', 'class' => 'form-control']) !!}
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-6">
                    <div class="form-group">
                        <Label class="req">Password</Label>
                        {!! Form::text('password', null, ['placeholder' => '', 'class' => 'form-control']) !!}
                    </div>
                </div>
              




            
            </div>




            <div class="row">
                <div class="col-md-2">
                    <button type="submit" class="btn btn-primary btn-block">Add</button>

                </div>
            </div>

            <script>
                $(document).ready(function() {


                    $('.form').validate({
                        rules: {
                            company_id: {
                                required: true
                            },
                            branch_id: {
                                required: true
                            },
                            username: {
                                required: true
                            },
                            password: {
                                required: true,
                                minlength: 6,
                                maxlength: 15
                            }

                        }
                    });
                });

            </script>


            {!! Form::close() !!}
        </div>
    </div>

@endsection

resources/views/tag_user/edit.blade.php
@extends('layouts.admin')

@section('content')
 
<div class="row">
  <div class="col-12"> <div class="page-title padleft20">Edit App User</div></div>
  <div class="col-6">
    <div class="btn">
          <a href="{{route('tag-user.index')}}" class="back btn-primary btn no-radius ">Back </a> 
      </div>
  </div>

  <div class="col-12"><div class="bottom-border"></div></div>
    

@if (count($errors) > 0)
  <div class="col-md-12">
  <div class="alert-message alert alert-danger">
    <Label>Whoops!</Label> There were some problems with your input.<br><br>
    <ul>
       @foreach ($errors->all() as $error)
         <li>{{ $error }}</li>
       @endforeach
    </ul>
  </div>
  </div>
  
@endif

  
</div><!--/.row-->
<div class="card mt-3">
  <div class="card-body">

  {!! Form::model($tagUser, ['method' => 'PATCH','autocomplete'=>'off','route' => ['tag-user.update', $tagUser->id],'class'=>'form']) !!}
  <div class="row">
    @if ($userInfo['companyListShow'])
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <Label class="req">Company List</Label>

                {!! Form::select('company_id', $companyList, null, ['placeholder' => 'Select Company', 'class'
                => 'form-control']) !!}
            </div>
        </div>
    @else
        {!! Form::hidden('company_id', $userInfo['company_id'], ['placeholder' => '', 'class' =>
        'form-control']) !!}

    @endif
    @if (!$userInfo['branch_id'])
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <Label class="req">Branch Name</Label>
                {!! Form::select('branch_id',$branches, null, ['placeholder' => 'Select Branch', 'class' =>
                'form-control']) !!}
            </div>
        </div>
    @else
        {!! Form::hidden('branch_id', $userInfo['branch_id'], ['placeholder' => '', 'class' => 'form-control'])
        !!}
    @endif



    <div class="col-xs-12 col-sm-12 col-md-6">
        <div class="form-group">
            <Label class="req">Login ID</Label>
            {!! Form::text('username', null, ['placeholder' => '', 'class' => 'form-control']) !!}
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-6">
        <div class="form-group">
            <Label class="req">Password</Label>
            {!! Form::text('password', null, ['placeholder' => '', 'class' => 'form-control']) !!}
        </div>
    </div>
  





</div>




<div class="row">
    <div class="col-md-2">
        <button type="submit" class="btn btn-primary btn-block">Save</button>

    </div>
</div>

<script>
    $(document).ready(function() {


        $('.form').validate({
            rules: {
                company_id: {
                    required: true
                },
                branch_id: {
                    required: true
                },
                username: {
                    required: true
                },
                password: {
                    required: true,
                    minlength: 6,
                    maxlength: 15
                }

            }
        });
    });

</script>

{!! Form::close() !!}
</div>
</div>

@endsection

resources/views/tag_user/index.blade.php
@extends('layouts.admin')

@section('content')
 
<div class="row">
  <div class="col-12"> <div class="page-title padleft20">App User List</div></div>
  @can('tag-user-create')
  <div class="col-6">
    <div class="btn">
          <a href="tag-user/create" class="add_new btn-primary btn no-radius ">Add New App User </a> 
      </div>
  </div>
  @endcan
  <div class="col-12"><div class="bottom-border"></div></div>
  <div class="col-md-12">
  @if ($message = Session::get('success'))
    <div class="alert alert-message alert-success">
        {{ $message }}
    </div>
@endif

  </div>

</div><!--/.row-->
<div class="card mt-3">
  <div class="card-body">
    <table class="table table-striped table-responsive1 mt-4">
        <thead>
          <tr>
            <th>Slno</th>
            <th>Company Name</th> 
            <th>Branch Name</th> 
            <th>Username</th> 
            <th>Date</th>
            <th>Action</th>
          </tr>

        </thead>
        <tbody>
        <input type="hidden" name="posted" value="1">
           
        @forelse($tag_users as $tag_user)
            <tr>
              <td>{{++$i}}</td>
              <td>{{$tag_user->company_name}}</td>
              <td>{{$tag_user->branch_name}}</td>
              <td>{{$tag_user->username}}</td>
              <td>
              <?php
              $created_at=$tag_user->created_at;
              if($created_at){
                echo date('d M Y, h:i a',strtotime($created_at));
              }
              ?>
              </td>
              <td class="action">
              
              @can('tag-user-create')
              <a href="{{ route('tag-user.edit',$tag_user->id) }}">
<i class="fas fa-pencil"></i> Edit
</a>&nbsp;&nbsp;&nbsp;
@endcan

@can('tag-user-delete')


<!-- Delete action -->
<a class="delete-icon" data-toggle="modal" data-target="#delete<?php echo $tag_user->id; ?>" ></a>
<div class="modal fade pp-modal" id="delete<?php echo $tag_user->id; ?>" tabindex="-1" role="dialog" aria-labelledby="ppModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center">
      	<div class="pp-icon"><i class="fas fa-question-square"></i></div>
        <h5 class="modal-title">Confirm</h5>
       <p>Are you sure, You want to delete <br> this record.</p>
      </div>
      <div class="modal-footer">
      	<div class="btn-list" style="display:block;">
        {!! Form::open(['method' => 'DELETE','class'=>"delete",'route' => ['tag-user.destroy', $tag_user->id]]) !!}
{!! Form::submit('Yes, Delete', ['class' => 'btn btn-danger ok']) !!}
{!! Form::close() !!} 

          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
	    </div>    
      </div>
    </div>
  </div>
</div>
<!-- End delete action  -->
@endcan

                
              </td>
              
              </tr>

              @empty
              <tr>
              <td colspan="7">
                <p class="text-center text-danger">No record found.</p>
              </td>
              </tr>
@endforelse

          
        </tbody>
      </table>
    

 
</div>
</div>

@endsection