routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return redirect('login');

});

Auth::routes();
Route::group(['middleware' => ['auth']], function() {

    Route::resource('roles','RoleController');    
    Route::get('/home', 'HomeController@index');
    Route::get('/change-password','UsersController@changePassword');
    Route::post('/change-password','UsersController@postChangePassword');
    Route::resource('/users','UsersController');
    Route::resource('/company','CompanyController');
    Route::get('/branchList/{companyId}','BranchController@branchList');
    Route::resource('/branch','BranchController');
    Route::resource('/tag-user','TagUserController');
    Route::resource('/zone','ZoneController');
    Route::get('/zoneList/{branchId}','ZoneController@zoneList');
    Route::get('/current-occupancy','CameraTransactionController@currentOccupancy');
    Route::get('/foot-fall','CameraTransactionController@footFall');
    Route::get('/violation','CameraTransactionController@violation');
    Route::post('/postzonesanitisation','HomeController@postZoneSanitisation');
    Route::get('/zone-notification','ZoneController@zoneNotification');

    #Route::get('/current-occupany','ZoneController@currentOccupany');
//currentOccupany
    Route::get('/device','CameraController@device');
    Route::get('/foot-fall-device/{id}','CameraTransactionController@footFallDevice')->name('foot_by_device');
    Route::resource('/camera','CameraController');
    Route::get('getZoneOccupancy','CameraTransactionController@getZoneOccupancy');
    Route::get('home-page','HomeController@homePage')->name('home');
    Route::get('chart_file_content','CameraTransactionController@chartFileContent')->name('chart_content');


});

app/Http/Controllers/Api/CameraTransactionController.php
<?php

namespace App\Http\Controllers\Api;
use Carbon\Carbon;
use Pusher\Pusher;
use App\User;
use App\Helpers\Common;
use Illuminate\Http\Request;
use App\Http\Controllers\ApiController;
use Validator;
use App\CameraTransaction;
use App\Camera;
use App\Zone;
use App\Branch;
use Illuminate\Support\Facades\DB;
use Config;
use Storage;
class CameraTransactionController extends ApiController
{
    private $defaultInterval;
    function __construct(){
        $this->defaultInterval=Config::get('app.chart_interval');
    }
    /**
 * @ Add camera request
 */
function addCameraTransaction(Request $request){
    $camera_input=Config::get('app.camera_input');
    if(!$camera_input){
        return "Camera request off. Please try again.";
    }

    $in       = $request->in;
    $out      = $request->out;
    $totalIn  = $in;
    $totalOut = $out;
    $totalNegative=0;
    $device   = $request->device;
    $device_mac=$request->device_mac;
    $current_occupancy =0;
    $zone_id  ="";
    $camera_id ="";
    $branch_id=0; 
    $branchStartTime="";
    $zone_total_in=0;
    $zone_total_enter=0;
    if(!$device){
        return "Device id missing";
    }
    // Camera::deviceUpdate($device);
    //  exit; 

    //Fetch device from camera table - Check device exist in db or not
    $camera = Camera::select('cameras.id','zone_id','reboot_type','max_occupancy','zones.branch_id','start_time','end_time')
    ->join('zones','zone_id','=','zones.id')
    ->join('branches','zones.branch_id','=','branches.id')    
    ->where('device_id',$device)->first();
        
    if($camera){
        $zone_id=$camera->zone_id;
        $reboot_type = $camera->reboot_type;
        $camera_id   = $camera->id;
        $max_occupancy=$camera->max_occupancy;
        $branch_id=$camera->branch_id;
        $branchStartTime=Common::getDateFromTime($camera->start_time);
        $branchTiming=[];
        $branchTiming['start_time']=$branchStartTime;
        $branchTiming['end_time']=Common::getDateFromTime($camera->end_time);;

        if(empty($start_time)){
            $this->notFound('Branch start time not set.');
        }
        
        $currentTime=Common::currentTime();
        if($currentTime>=$branchTiming['start_time'] && $currentTime<=$branchTiming['end_time']){

        }
        else{
            return "Current time not valid with site time";
        }
        //Save device status in db 
        // $camera->last_request=Common::currentTime();
        // $camera->save();
        


        //If device reboot type is interrupt then data is not insert. Return false
        if($reboot_type=='interrupt'){
            $data['status']  = false;
            $data['message'] = "Rebot type - interrupt. Transaction is not added.";
            $data['data']    = [];
            return $this->sendResponse($data);
        }
    }
    else{
        return "Device not found"; 
    }
   //End Fetch device from camera table 

    //Fetch zone max_occupancy
    // $zoneRow =Zone::select('max_occupancy','branch_id')
    //             ->join('branches','branch_id','=','branches.id')
    //             ->where('zones.id',$zone_id)->first();   
            
    // if(!$zoneRow){
    //     $this->notFound('Invalid zone id. Please try again!');
    // }                   
    // $max_occupancy=$zoneRow->max_occupancy;
    // $branch_id=$zoneRow->branch_id;
    // if(empty($branch_id)){
    //     $this->notFound('Invalid branch id. Please try again!');
    // }
    //End Fetch zone max_occupancy
    
    //Fetch branch start time
    // if($branch_id){
    //     $branchStartTime=Branch::branchStartTime($branch_id);
    // }
    // if(empty($branchStartTime)){
    //     $this->notFound('Branch start time not set!');
    // }
    
    //Fetch all device id for this zone except current device
    $cameras =Camera::select('id')->where('zone_id',$zone_id)
                     ->where('id','<>',$camera_id)
                     ->get();
                     
   
    if($cameras){
        foreach($cameras as $cameraDevice){
            //Fetch camera id
            $cameraDeviceId = $cameraDevice->id;
            
            //Fetch this device last entry in camera transaction table
            if($cameraDeviceId){
                $cameraTransaction = CameraTransaction::select('in','out')
                                    ->where('camera_id',$cameraDeviceId)
                                    ->where('created_at','>=',$branchStartTime)
                                    ->orderBy('id','desc')
                                    ->first();
                                   
                //If record exists then fetch in,out and sum in totalIn,totalOut
                if($cameraTransaction){
                    $totalIn+=$cameraTransaction->in;
                    $totalOut+=$cameraTransaction->out;
                }                    
            } 
        }
    }
 
    
    //Fetch all negative value for this zone greater then branch start time and value less than 0
    $totalNegative = CameraTransaction::where('zone_id',$zone_id)
                                    ->where('delta_in_out','<',0)
                                    ->where('created_at','>=',$branchStartTime)
                                    ->sum('delta_in_out');
                                   
                                   
                             

    //Calculate occupancy = totalIn-(totalOut+totalNegative)
    $calculatedOccupancy  = $totalIn-($totalOut+$totalNegative); 
    $current_occupancy    = $calculatedOccupancy; 
    $delta_in_out         = $calculatedOccupancy; 

    //Zone total in 
    $zone_total_in = $totalIn;
    
    //Calculate zone total enter= $zone_total_in- find last entry from this zone
    $zoneLastTransaction = CameraTransaction::select('zone_total_in')
                            ->where('zone_id',$zone_id)
                            ->where('created_at','>=',$branchStartTime)
                            ->orderBy('id','desc')
                            ->first();
                           
                            
    if($zoneLastTransaction){
        $previousZoneTotalIn=$zoneLastTransaction->zone_total_in;
        $zone_total_enter=$zone_total_in-$previousZoneTotalIn;
        if($zone_total_enter<0){
            $zone_total_enter=0;
        }
    }    
   
    // If current occupancy less than 0 then set 0
    if($current_occupancy<0){
        $current_occupancy=0;
    }

    $occupancy_violation=0;
    $data=[];
   // echo $current_occupancy."=".$max_occupancy; exit; 
    //If zone has has set max occupancy then go to if block
    if($max_occupancy){
        //If current_occupancy greater than zone max occupancy
         if($current_occupancy>$max_occupancy){
            // $occupancy_violation=1;
             $violationCheck = CameraTransaction::where(['zone_id'=>$zone_id,'occupancy_violation'=>1])
                               ->whereNull('violation_end')    
                               ->orderBy('id','desc')
                               ->take(1)
                               ->get()
                               ->count(); 
                              // Common::queryLog();
                      
             if($violationCheck){
                $occupancy_violation=2;
             }                   
             else{
                $occupancy_violation=1;
                $data['violation_start']=date('Y-m-d H:i:s');
             }
         }
         else{
            $occupancy_violation=0;

            // If current_occupancy less than zone max occupancy
            $violationCheck = CameraTransaction::where(['zone_id'=>$zone_id,'occupancy_violation'=>1])
                                ->whereNull('violation_end')    
                                ->orderBy('id','desc')
                                ->first();
                              
            if($violationCheck){
                $violationCheck->id;
                $currentTime=date('Y-m-d H:i:s');
                $violationCheck->violation_end=$currentTime;
               
                $from_time=strtotime($violationCheck->violation_start); 
                $to_time=strtotime($currentTime);
                $duration = round(abs($to_time - $from_time) / 60,2);
                $violationCheck->violation_duration=$duration;
                $violationCheck->save();    
               
            }                   
             $occupancy_violation=0;
         }  

    }
   
    //Find last total entry
    //Total entry last entry - current in 
    $lastEntry =CameraTransaction::findLastRecord($device,'in');
   

    $entry = $in-$lastEntry; 
    if($entry<0){
        $entry=0;
    }
    
    $data['enter']=$entry;
    $data['in']=$in;
    $data['out']=$out;
    $data['current_occupancy']=$current_occupancy;
    $data['device']=$device;
    $data['device_mac']=$device_mac;
    $data['occupancy_violation']=$occupancy_violation;
    $data['zone_id']=$zone_id;
    $data['camera_id']=$camera_id;
    // $data['base_in']=$base_in;
    // $data['base_out']=$base_out;
    $data['delta_in_out']=$delta_in_out;
    $data['zone_total_in']=$zone_total_in;
    $data['zone_total_enter']=$zone_total_enter;
    
    //Save data in file for chart
    // $branch=Branch::select('start_time','end_time')
    // ->where('id',$branch_id)
    // ->first();
    
    // $start_time="";
    // $end_time="";
    // if($branch){
    //     $start_time=$branch->start_time;
    //     $end_time=$branch->end_time;
    //     if($start_time){
    //       $start_time = date('Y-m-d H:i:s',strtotime($start_time));
    //     }
    //     if($end_time){
    //         $end_time = date('Y-m-d H:i:s',strtotime($end_time));
    //     }
    // }
    // $branchTiming=[];
    // $branchTiming['start_time']=$start_time;
    // $branchTiming['end_time']=$end_time;
    

   
    /**
     * Write data in file for chart display- 
     */
    //  $currentTime=date('Y-m-d H:i:s');

resources/views/camera-transaction/create.blade.php
@extends('layouts.admin')

@section('content')

    <div class="row">
        <div class="col-12">
            <div class="page-title padleft20">Add New Camera</div>
        </div>
        <div class="col-6">
            <div class="btn">
                <a href="{{ url('camera') }}" class="back btn-primary btn no-radius ">Back </a>
            </div>
        </div>

        <div class="col-12">
            <div class="bottom-border"></div>
        </div>


        @if (count($errors) > 0)
            <div class="col-md-12">
                <div class="alert-message alert alert-danger">
                    <Label>Whoops!</Label> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            </div>

        @endif


    </div>
    <!--/.row-->
    <div class="card">
        <div class="card-body">


            {!! Form::open(['route' => 'camera.store', 'method' => 'POST', 'class' => 'form']) !!}
            <div class="row">
                @if ($userInfo['companyListShow'])
                    <div class="col-xs-12 col-sm-12 col-md-6">
                        <div class="form-group">
                            <Label class="req">Company List</Label>

                            {!! Form::select('company_id', $companyList, null, ['placeholder' => 'Select Company', 'class'
                            => 'form-control']) !!}
                        </div>
                    </div>
                @else
                    {!! Form::hidden('company_id', $userInfo['company_id'], ['placeholder' => '', 'class' =>
                    'form-control']) !!}

                @endif
                
                @if (!$userInfo['branch_id'])
                <div class="col-xs-12 col-sm-12 col-md-6">
                    <div class="form-group">
                        <Label class="req">Branch Name</Label>
                        {!! Form::select('branch_id', $branches, null, ['placeholder' => 'Select Branch', 'class' =>
                        'form-control zoneByBranch']) !!}
                    </div>
                </div>
                @else
                {!! Form::hidden('branch_id', $userInfo['branch_id'], ['placeholder' => '', 'class' =>
                'form-control ']) !!}
                @endif



                

                <div class="col-xs-12 col-sm-12 col-md-6">
                    <div class="form-group">
                        <Label class="req">Zone Name</Label>
                        {!! Form::select('zone_id', [], null, ['id'=>'zone_id','placeholder' => 'Select Floor', 'class' =>
                        'form-control']) !!}
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-6">
                    <div class="form-group">
                        <Label class="req">Device Name</Label>
                        {!! Form::text('device_name', null, ['class' => 'form-control']) !!}
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-6">
                    <div class="form-group">
                        <Label class="req">Device Id</Label>
                        {!! Form::text('device_id', null, ['class' => 'form-control']) !!}
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-6">
                    <div class="form-group">
                        <Label class="req">Device Mac</Label>
                        {!! Form::text('device_mac', null, ['class' => 'form-control']) !!}
                    </div>
                </div>
                {{-- <div class="col-xs-12 col-sm-12 col-md-6">
                    <div class="form-group">
                        <Label class="req">Maximum</Label>
                        {!! Form::number('maximum', null, ['class' => 'form-control']) !!}
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-6">
                    <div class="form-group">
                        <Label class="req">Area</Label>
                        {!! Form::textarea('area', null, ['class' => 'form-control','rows'=>3]) !!}
                    </div>
                </div> --}}




             

            </div>

<div class="row mt-3 float-left w-100">
                <div class="col-md-2">
                    <button type="submit" class="btn btn-primary btn-block">Add</button>

                </div>
            </div>



         
            <script>
                $(document).ready(function() {

                    $('.form').validate({
                        rules: {
                            company_id: {
                                required: true
                            },
                            branch_id: {
                                required: true
                            },
                            zone_id: {
                                required: true
                            },
                            camera_name: {
                                required: true
                            }
                        }
                    });
                });

            </script>


            {!! Form::close() !!}
        </div>
    </div>

@endsection

resources/views/camera-transaction/current-occupancy.blade.php
@extends('layouts.admin')

@section('content')
    <div class="row">
        <div class="col-12">
            <h5>Occupancy </h5>
        </div>
    </div>
    <!--/.row-->
    <div class="row">
        <div class="col-md-12">
            <form action="" method="get" autocomplete="off">
                <div class="row">
                    <div class="form-group col-xs-12 col-sm-12 col-md-2 ">
                        {!! Form::select('zone_id', $data['zone_names'], app('request')->input('zone_id'), ['placeholder' => 'Select Zone', 'class' => 'form-control']) !!}
                    </div>

                    <div class="col-sm-12 col-md-2">
                        <?php
                        $filter_date = app('request')->input('filter_date');
                        if ($filter_date) {
                        $filter_date = date('d-m-Y', strtotime($filter_date));
                        }
                        ?>
                        <input type="text" id="filter_date" value="{{ $filter_date }}" class="form-control datepicker"
                            name="filter_date" placeholder="" autocomplete="off">
                    </div>
                    <div class="col-sm-12 col-md-2">
                        <input type="submit" value="GO" class="btn btn-primary full-width">

                    </div>
                </div>
            </form>
        </div>
    </div>
    <!--/.col-12-->
    <div class="row">
        <div class="col-12">
        <div class="card zoom-card panel-box radius-10">
            <div class="card-body">
                <p class="no-bottom-margin zoom-info"><span class="bold-text">Zoomable Statistic</span> : Select the range in the chart you want to zoom in</p>
            </div>
        </div>
        </div>
    </div>         


    <?php
    $zones = $data['zones'];

    if ($zones) {
    foreach ($zones as $key => $zone) {
    $zone_id = $zone['id']; ?>
    <div class="row">
        <div class="col-md-12">
            <div class="card panel-box-width panel-box radius-10">
                <div class="card-header">
                    <h6>{{ $zone['zone_name'] }} Overview</h6>
                </div>
                <div class="card-body">
                    <div class="chart-container-1">
                        <div id="zone_chart_{{ $zone['id'] }}" class="chart-container-1"></div>
                        {{-- <div id="watermark-{{ $zone['id'] }}" class="watermark none">No Data</div> --}}
                    </div>

                </div>

            </div>
        </div>
    </div>



    <?php
    }
    }
    ?>
    <script>
        <?php if ($zones) {
                foreach ($zones as $key => $zone) {

                    $file_url = $zone->file_url;
                    $zoneId = $zone->id;
                    ?>
        chartData = {
            ...highchartOption
        };
        //var updateChart = window[`zone_${zone_id}`];

        //window[`highChart_{{ $zoneId }}`].data.csvURL = occupancyFileUrl;
        chartData.data.csvURL = `{{ $file_url }}`;
        Highcharts.chart("zone_chart_{{ $zoneId }}", chartData);
        <?php
                }
            } ?>
    </script>








@endsection

resources/views/camera-transaction/edit.blade.php
@extends('layouts.admin')

@section('content')

<div class="row">
  <div class="col-12"> <div class="page-title padleft20">Edit camera</div></div>
  <div class="col-6">
    <div class="btn">
          <a href="{{route('camera.index')}}" class="back btn-primary btn no-radius ">Back </a> 
      </div>
  </div>

  <div class="col-12"><div class="bottom-border"></div></div>
    

@if (count($errors) > 0)
  <div class="col-md-12">
  <div class="alert-message alert alert-danger">
    <Label>Whoops!</Label> There were some problems with your input.<br><br>
    <ul>
       @foreach ($errors->all() as $error)
         <li>{{ $error }}</li>
       @endforeach
    </ul>
  </div>
  </div>
  
@endif

  
</div><!--/.row-->
<div class="card mt-3">
  <div class="card-body">

  {!! Form::model($camera, ['method' => 'PATCH','autocomplete'=>'off','route' => ['camera.update', $camera->id]]) !!}
  <div class="row">
    @if ($userInfo['companyListShow'])
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <Label class="req">Company List</Label>

                {!! Form::select('company_id', $companyList, null, ['placeholder' => 'Select Company', 'class'
                => 'form-control']) !!}
            </div>
        </div>
    @else
        {!! Form::hidden('company_id', $userInfo['company_id'], ['placeholder' => '', 'class' =>
        'form-control']) !!}

    @endif
    
    @if (!$userInfo['branch_id'])
    <div class="col-xs-12 col-sm-12 col-md-6">
        <div class="form-group">
            <Label class="req">Branch Name</Label>
            {!! Form::select('branch_id', $branches, null, ['placeholder' => 'Select Branch', 'class' =>
            'form-control zoneByBranch']) !!}
        </div>
    </div>
    @else
    {!! Form::hidden('branch_id', $userInfo['branch_id'], ['placeholder' => '', 'class' =>
    'form-control']) !!}
    @endif




  
    <div class="col-xs-12 col-sm-12 col-md-6">
        <div class="form-group">
            <Label class="req">Zone Name</Label>
            {!! Form::select('zone_id', $zones, null, ['id'=>'zone_id','placeholder' => 'Select Floor', 'class' =>
            'form-control']) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6">
        <div class="form-group">
            <Label class="req">Device Name</Label>
            {!! Form::text('device_name', null, ['class' => 'form-control']) !!}
        </div>
    </div>


    <div class="col-xs-12 col-sm-12 col-md-6">
        <div class="form-group">
            <Label class="req">Device Id</Label>
            {!! Form::text('device_id', null, ['class' => 'form-control']) !!}
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-6">
        <div class="form-group">
            <Label class="req">Device Mac</Label>
            {!! Form::text('device_mac', null, ['class' => 'form-control']) !!}
        </div>
    </div>
  


 
  


</div>












<div class="row mt-3">
    <div class="col-md-2">
        <button type="submit" class="btn btn-primary btn-block">Save</button>

    </div>
</div>




<script>
    $(document).ready(function() {

    



       
                    $('.form').validate({
                        rules: {
                            company_id: {
                                required: true
                            },
                            branch_id: {
                                required: true
                            }
                            

                        }
                    });
                });

 

</script>



{!! Form::close() !!}
</div>
</div>

@endsection

resources/views/camera-transaction/index.blade.php
@extends('layouts.admin')

@section('content')
 
<div class="row">
  <div class="col-12"> <div class="page-title padleft20">Camera List</div></div>
  @can('camera-create')
  <div class="col-6">
    <div class="btn">
          <a href="camera/create" class="add_new btn-primary btn no-radius ">Add New Camera </a> 
      </div>
  </div>
  @endcan
  <div class="col-12"><div class="bottom-border"></div></div>
  <div class="col-md-12">
  @if ($message = Session::get('success'))
    <div class="alert alert-message alert-success">
        {{ $message }}
    </div>
@endif

  </div>

</div><!--/.row-->
<div class="card mt-3">
  <div class="card-body">
    <table class="table table-striped table-responsive1 mt-4">
        <thead>
          <tr>
            <th>Slno</th>
            <th>Company Name</th> 
            <th>Branch Name</th> 
           <th>Zone Name</th> 
            <th>Device Name</th> 
            <th>Device Id</th> 
            <th>Device Mac</th> 
            <th>Date</th>
            <th>Action</th>
          </tr>

        </thead>
        <tbody>
        <input type="hidden" name="posted" value="1">
           
        @forelse($data as $row)
            <tr>
              <td>{{++$i}}</td>
              <td>{{$row->company_name}}</td>
              <td>{{$row->branch_name}}</td>
              <td>{{$row->zone_name}}</td>
              <td>{{$row->device_name}}</td>
              <td>{{$row->device_id}}</td>
              <td>{{$row->device_mac}}</td>
              <td>
              <?php
              $created_at=$row->created_at;
              if($created_at){
                echo date('d M Y, h:i a',strtotime($created_at));
              }
              ?>
              </td>
              <td class="action">
              
              @can('camera-create')
              <a href="{{ route('camera.edit',$row->id) }}">
<i class="fas fa-pencil"></i> Edit
</a>&nbsp;&nbsp;&nbsp;
@endcan

@can('camera-delete')


<!-- Delete action -->
<a class="delete-icon" data-toggle="modal" data-target="#delete<?php echo $row->id; ?>" ></a>
<div class="modal fade pp-modal" id="delete<?php echo $row->id; ?>" tabindex="-1" role="dialog" aria-labelledby="ppModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center">
      	<div class="pp-icon"><i class="fas fa-question-square"></i></div>
        <h5 class="modal-title">Confirm</h5>
       <p>Are you sure, You want to delete <br> this record.</p>
      </div>
      <div class="modal-footer">
      	<div class="btn-list" style="display:block;">
        {!! Form::open(['method' => 'DELETE','class'=>"delete",'route' => ['camera.destroy', $row->id]]) !!}
{!! Form::submit('Yes, Delete', ['class' => 'btn btn-danger ok']) !!}
{!! Form::close() !!} 

          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
	    </div>    
      </div>
    </div>
  </div>
</div>
<!-- End delete action  -->
@endcan

                
              </td>
              
              </tr>

              @empty
              <tr>
              <td colspan="8">
                <p class="text-center text-danger">No record found.</p>
              </td>
              </tr>
@endforelse

          
        </tbody>
      </table>
    

 
</div>
</div>

@endsection

resources/views/camera-transaction/occupancy-violation.blade.php
@extends('layouts.admin')

@section('content')
    <div class="row">
        <div class="col-12">
            <h5> Occupancy Violation</h5>
        </div>
    </div>
    <!--/.row-->
    <div class="row">
        <div class="col-md-12">
            <form action="" method="get" autocomplete="off">
                <div class="row">
                    <div class="form-group col-xs-12 col-sm-12 col-md-2 ">
                        {!! Form::select('zone_id', $data['zone_names'], app('request')->input('zone_id'), ['placeholder' => 'Select Zone', 'class' => 'form-control']) !!}
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-2">
                        <?php
                        $filter_date = app('request')->input('filter_date');
                        if ($filter_date) {
                            $filter_date = date('d-m-Y', strtotime($filter_date));
                        }
                        ?>
                        <input type="text" id="filter_date" value="{{ $filter_date }}" class="form-control datepicker"
                            name="filter_date" placeholder="" autocomplete="off">
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-2">
                        <input type="submit" value="GO" class="btn btn-primary full-width">

                    </div>
                </div>
            </form>
        </div>
    </div>
    <!--/.col-12-->

    <div class="row">
        <div class="col-12">
        <div class="card zoom-card panel-box radius-10">
            <div class="card-body">
                <p class="no-bottom-margin zoom-info"><span class="bold-text">Zoomable Statistic</span> : Select the range in the chart you want to zoom in</p>
            </div>
        </div>
        </div>
    </div>

    <?php
    $zones = $data['zones'];

    if ($zones) {
    foreach ($zones as $key => $zone) {
    $zone_id = $zone['id']; ?>
    <div class="row">
        <div class="col-md-12">
            <div class="card panel-box-width panel-box radius-10">
                <div class="card-header">
                    <h6>{{ $zone['zone_name'] }} Overview
                        @if (!$zone['max_occupancy'])
                            | <a href="{{ route('zone.edit', $zone_id) }}">Set Threshold</a>
                        @endif
                    </h6>
                </div>
                <div class="card-body">
                    <div class="chart-container-1">
                        @if ($zone['max_occupancy'])
                            <div id="zone_chart_{{ $zone['id'] }}" class="chart-container-1"></div>
                        @else
                            <div id="watermark-{{ $zone['id'] }}" class="watermark">Max threshold not set</div>
                        @endif
                    </div>

                </div>

            </div>
        </div>
    </div>



    <?php
    }
    }
    ?>
    <script>
        <?php if ($zones) {
                foreach ($zones as $key => $zone) {

                    $file_url = $zone->file_url;
                    $zoneId = $zone->id;
                    ?>
        chartData = {
            ...highchartOption
        };
        //var updateChart = window[`zone_${zone_id}`];

        //window[`highChart_{{ $zoneId }}`].data.csvURL = occupancyFileUrl;
        chartData.data.csvURL = `{{ $file_url }}`;
        Highcharts.chart("zone_chart_{{ $zoneId }}", chartData);
        <?php
                }
            } ?>
    </script>








@endsection